name: Static Analysis

# Run on pull requests and by dispatch
on:
  workflow_dispatch:
  pull_request:

jobs:
  static-analysis:
    name: Run cppcheck
    uses: nasa/cFS/.github/workflows/static-analysis.yml@main
    with:
      strict-dir-list: './lib/src ./common/src ./cache/src ./v7/src ./os/src ./store'
